name: Unit Tests

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'Decide/DecideDocs.docc/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'Decide/DecideDocs.docc/**'

jobs:
  build:
    runs-on: macos-13
    steps:
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.9
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test
