name: Unit Tests

on:
  push:
    branches: 
    - main
    paths-ignore:
    - 'Sources/Decide.docc/**'
  pull_request:
    branches: 
    - main
    paths-ignore:
    - 'Sources/Decide.docc/**'

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: swift test -v
